name: Docker Image Release Build

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-18.04
    env:
      GH_IMAGE: ghcr.io/itu-auv/auv-jetson-docker:melodic-${{ github.job }}
    steps:
      # Checkout
      - name: Checkout 
        uses: actions/checkout@v2

      # Setup Docker
      # - name: Setup Docker
      #  uses: docker-practice/actions-setup-docker@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # Login to ghcr.io for docker
      - name: Login to Github Containter Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Build & Push Docker Image
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          build-args: |
            ROS_DISTRO=melodic 
            ROS_PKG=desktop_full 
            BASE_IMAGE=nvcr.io/nvidia/l4t-base:r32.5.0
          push: true
          no-cache: ${{ steps.apt.outputs.no_cache || github.event_name == 'workflow_dispatch' }}
          cache-from: type=registry,ref=${{ env.GH_IMAGE }}
          cache-to: type=inline
          tags: |
            ${{ env.GH_IMAGE }}
